server:
  port: 8191
  
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sathik53/spring-cloud-config-store.git
          search-paths: 
          - '*service'
          #username: root
          #password: root
          